version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        - REACT_APP_API_URL=http://3.110.167.179:8000
    container_name: pos_frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    stdin_open: true
    tty: true