name: Deploy Frontend and Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy project files to EC2
        run: |
          ssh-keyscan -H 13.203.198.46 >> ~/.ssh/known_hosts

          # Copy frontend
          rsync -avz --exclude=node_modules --exclude=.git ./frontend ubuntu@13.203.198.46:/home/ubuntu/pos-frontend

          # Copy backend
          rsync -avz --exclude=node_modules --exclude=.git ./backend ubuntu@13.203.198.46:/home/ubuntu/pos-backend

      - name: SSH into EC2 and deploy both apps
        run: |
          ssh ubuntu@13.203.198.46 << 'EOF'
            # FRONTEND DEPLOYMENT
            cd pos-frontend
            docker stop pos-frontend-container || true
            docker rm pos-frontend-container || true
            docker rmi pos-frontend || true
            docker build -t pos-frontend .
            docker run -d -p 5173:5173 --name pos-frontend-container pos-frontend

            # BACKEND DEPLOYMENT
            cd ../pos-backend
            docker stop pos-backend-container || true
            docker rm pos-backend-container || true
            docker rmi pos-backend || true
            docker build -t pos-backend .
            docker run -d -p 8000:8000 --name pos-backend-container pos-backend
          EOF
