name: Frontend Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug - List Repository Files
        run: ls -R  # Check if 'pos-frontend' exists

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          if [ -d "pos-frontend" ]; then
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest ./pos-frontend
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest
          else
            echo "Error: 'pos-frontend' directory not found!"
            exit 1
          fi

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest
            docker stop pos-frontend || true
            docker rm pos-frontend || true
            docker run -d -p 3000:3000 --name pos-frontend \
              ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest
