name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - frontend/**  # Trigger when changes occur in frontend directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          docker build -t frontend-app ./frontend
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker tag frontend-app ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app
            git pull origin main
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest
            docker compose up -d
