name: Deploy Frontend

on:
  push:
    paths:
      - 'pos-frontend/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug - List Repository Files
        run: ls -R  # Check if pos-frontend exists

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest ./pos-frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/pos-app
            docker-compose down
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest
            docker-compose up -d --force-recreate
            docker system prune -f
            docker ps -a
