name: Deploy Frontend

on:
  push:
    branches:
      - new_staging_test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY}}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest
            docker-compose up -d
            docker system prune -f
