name: Deploy Frontend

on:
  push:
    branches:
      - new_staging_test
    paths:
      - 'pos-frontend/**'  # Trigger only when frontend files change

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd pos-frontend  # Ensure we are in the correct directory
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pos-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/pos-frontend:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/pos-deployment
            docker-compose pull pos-frontend  # Pull only frontend image
            docker-compose up -d pos-frontend  # Restart only frontend container
