name: Deploy Frontend

on:
  push:
    branches:
      - new_staging_test
    paths:
      - "pos-frontend/**"  # Runs only when files in pos-frontend change

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest ./pos-frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/pos-app  # Navigate to the correct directory
            docker-compose down  # Stop running containers
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pos-frontend:latest  # Pull the latest image
            docker-compose up -d --force-recreate  # Start fresh containers
            docker system prune -f  # Cleanup unused images
            docker ps -a  # Check running containers
            docker logs $(docker ps -aq --filter "name=pos-frontend")  # Debug logs
